spring.application.name=Cenit
# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/cenit
spring.datasource.username=postgres
spring.datasource.password=Admin777

# JPA — Hibernate no toca la BD, Flyway se encarga
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway — aplica los .sql de db/migration automáticamente
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
